version: '3.4'

services:
  aspnetcore.authentication.wapp:
    image: ${DOCKER_REGISTRY-}wapp
    build:
      context: .
      dockerfile: AspNetCore.Authentication.WApp/Dockerfile
    depends_on:
      - aspnetcore.authentication.webapitwo
      - aspnetcore.authentication.webapithree

  aspnetcore.authentication.webapitwo:
    image: ${DOCKER_REGISTRY-}webapitwo
    build:
      context: .
      dockerfile: AspNetCore.Authentication.WebApiTwo/Dockerfile


  aspnetcore.authentication.webapithree:
    image: ${DOCKER_REGISTRY-}webapithree
    build:
      context: .
      dockerfile: AspNetCore.Authentication.WebApiThree/Dockerfile
