name: Build .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Microsoft.AspNetCore.Authentication.Keycloak

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --tags
          git branch --create-reflog master origin/master
      
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
          
      - name: Build
        run: dotnet build --configuration Release  
