name: Publish NuGet

on:
  push:
    branches: [ master ]
    
jobs:
  publish:
    
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history


      - name: Git Version
        id: git-version
        uses: codacy/git-version@2.2.0


      - uses: Mudlet/xmlstarlet-action@master
        with:
          args: ed --update /Project//PropertyGroup/Version --value {{ steps.git-version.output.version }}


      - name: Publish Nuget.org
        uses: myci-actions/publish-nuget@2
        with:
          filename: src/Jboss.AspNetCore.Authentication.Keycloak/Jboss.AspNetCore.Authentication.Keycloak.csproj
          api-key: ${{ secrets.NUGET_SECRET }}
          repo-url: https://api.nuget.org/v3/index.json
          
          
      - name: Publish GitHub
        uses: myci-actions/publish-nuget@2
        with:
          filename: src/Jboss.AspNetCore.Authentication.Keycloak/Jboss.AspNetCore.Authentication.Keycloak.csproj
          api-key: ${{ secrets.SECRET }}
          repo-url: https://nuget.pkg.github.com/elmankross/index.json
