name: Publish NuGet

on:
  push:
    branches: [ master ]
    
jobs:
  publish:
    
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history


      - name: Git Version
        uses: codacy/git-version@2.2.0


      - name: Publish Nuget.org
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Jboss.AspNetCore.Authentication.Keycloak/Jboss.AspNetCore.Authentication.Keycloak.csproj
          NUGET_KEY: ${{secrets.NUGET_SECRET}}
          NUGET_SOURCE: https://api.nuget.org
          
          
      - name: Publish GitHub
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Jboss.AspNetCore.Authentication.Keycloak/Jboss.AspNetCore.Authentication.Keycloak.csproj
          NUGET_KEY: ${{secrets.GITHUB_TOKEN}}
          NUGET_SOURCE: https://nuget.pkg.github.com/elmankross
