name: Publish NuGet

on:
  push:
    branches: [ master ]
   
env:
  PROJECT_FILE: src/Jboss.AspNetCore.Authentication.Keycloak/Jboss.AspNetCore.Authentication.Keycloak.csproj

jobs:
  publish:
    
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        id: git-version
        uses: codacy/git-version@2.2.0

      - uses: Mudlet/xmlstarlet-action@master
        with:
          args: ed --update /Project//PropertyGroup/Version --value ${{ steps.git-version.output.version }} ${{ env.PROJECT_FILE }}

      - name: Publish to nuget.org
        uses: Rebel028/publish-nuget@v2.6.0
        with:
          PROJECT_FILE_PATH: ${{ env.PROJECT_FILE }}
          NUGET_KEY: ${{ secrets.NUGET_SECRET }}
          NUGET_SOURCE: https://api.nuget.org
          TAG_FORMAT: '*'
          #VERSION_STATIC: ${{ steps.git-version.output.version }}    
          
      - name: Publish to gitHub
        uses: Rebel028/publish-nuget@v2.6.0
        with:
          PROJECT_FILE_PATH: ${{ env.PROJECT_FILE }}
          NUGET_KEY: ${{ secrets.SECRET }}
          NUGET_SOURCE: https://nuget.pkg.github.com/elmankross
          TAG_FORMAT: '*'
          #VERSION_STATIC: ${{ steps.git-version.output.version }}
